version: '3.3'
services:
    mysql:
        image: mysql:5.3
        restart: always
        environment:
            MYSQL_USER: "everton.b"
            MYSQL_PASSWORD: "mypassword"
            MYSQL_ROOT_PASSWORD: "root"
        volumes:
            - '/storage/docker/mysql-datadir:/var/lib/mysql'
        ports:
            - "3306:3306"
    api:
        build: ./api
        restart: always
        volumes:
            - '/tmp:/tmp/images/'
        depends_on:
            - mysql
        ports:
            - '80:80'